**welcome to numpy tutorial**

# welcome to tutorial 

 ** search markdown keyword **

In [4]:
import numpy as np
# shift enter for new shell

In [5]:
print("hello")

hello


In [6]:
import numpy as np

myarr=np.array([3,6,1])

print(myarr)

myarr3=np.array([[3,61,7]],np.int8) # 8 bit integer 
myarr2=np.array([[3,1,6]],np.int32) # 32 bit integer 
myarr1=np.array([[3,6,1]],np.int64) # 64
print(myarr1)
print(myarr1[0])
print(myarr1[0,1])
print(myarr1.shape)
print(myarr.dtype)


[3 6 1]
[[3 6 1]]
[3 6 1]
6
(1, 3)
int32


In [7]:
# numpy type referance

In [8]:
myarr1[0,1]=45

In [9]:
  # array creation method in numpy 

In [10]:
# https://numpy.org/doc/stable/user/basics.creation.html

# array creation: conversion from other python structure 

In [12]:
listarray=np.array([[1,2,3],[1,2,3],[1,2,3]])

In [13]:
listarray

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [14]:
listarray.dtype

dtype('int32')

In [15]:
listarray.shape

(3, 3)

In [16]:
listarray.size

9

In [17]:
np.array({1,2,3,7})

array({1, 2, 3, 7}, dtype=object)

In [18]:
zeros=np.zeros((2,5))

In [19]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
rng=np.arange(5)

In [21]:
rng

array([0, 1, 2, 3, 4])

In [22]:
lspace=np.linspace(1,5,3)

In [23]:
lspace

array([1., 3., 5.])

In [24]:
emp=np.empty((4,6)) # empty array of size 4 , 6 and having randome values 

In [25]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        7.56595733e-307, 7.56587585e-307, 1.37961302e-306],
       [1.05699242e-307, 8.01097889e-307, 1.78020169e-306,
        7.56601165e-307, 1.02359984e-306, 1.42417221e-306],
       [7.56593017e-307, 1.37961302e-306, 1.11259940e-306,
        1.60219035e-306, 1.33511018e-306, 8.90092016e-307],
       [9.79098366e-307, 9.34605037e-307, 1.37962320e-306,
        1.37961302e-306, 2.22522596e-306, 8.34423917e-308]])

In [26]:
emp_like=np.empty_like(lspace)

In [27]:
emp_like

array([7.74860419e-304, 7.74860419e-304, 7.74860419e-304])

In [28]:
ide=np.identity(45)

In [29]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [30]:
ide.shape

(45, 45)

In [31]:
arr=np.arange(99)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [33]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [35]:
arr1=np.arange(99)

In [36]:
arr1=arr1.reshape(3,33)

In [37]:
arr1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [38]:
arr1.ravel() # return the matrix of its initial form 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [39]:
arr.shape

(99,)

In [40]:
x=[[1, 2, 3], [4, 5, 6]]

In [41]:
arr = np.array(x)

In [42]:
arr.sum(axis=0)

array([5, 7, 9])

In [43]:
arr.sum(axis=1)

array([ 6, 15])

In [44]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [45]:
y=[[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]

In [46]:
arr1= np.array(y)

In [47]:
arr1

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [48]:
arr1.flat

In [49]:
for item in arr1.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [50]:
arr1.ndim

3

In [51]:
arr1.size

9

In [52]:
arr1.nbytes

36

# one d array

In [54]:
one=np.array([3,6,1])  

In [55]:
one.argmax() # asa the function hai naki attribute # 

1

In [56]:
one.argmin()

2

In [57]:
one.argsort()

array([2, 0, 1], dtype=int64)

In [58]:
arr1

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [59]:
arr1.argsort()

array([[[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]], dtype=int64)

In [60]:
arr1.argmin() # shidha krne ke baad minimum element  nnikal raha hai bs 

0

In [61]:
arr1.argmax()

8

In [62]:
arr1.argmax(axis=1) 

array([[2, 2, 2]], dtype=int64)

In [63]:
arr1.argsort(axis=1) 

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]]], dtype=int64)

In [64]:
arr1.argmax(axis=2) 

array([[2, 2, 2]], dtype=int64)

In [65]:
arr1.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
arr1

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [67]:
arr1.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
arr1.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [69]:
arr1.reshape((9,))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

**matrix multiplication**

In [71]:
z=[[ 1,2,3],[4,5,6],[7,8,9]]

In [72]:
ar2=np.array(z)

In [73]:
a=[[7,8,9],[4,5,6],[1,1,1]]

In [74]:
ar1=np.array(a)

In [75]:
ar1

array([[7, 8, 9],
       [4, 5, 6],
       [1, 1, 1]])

In [76]:
ar1

array([[7, 8, 9],
       [4, 5, 6],
       [1, 1, 1]])

In [77]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
ar1+ar2

array([[ 8, 10, 12],
       [ 8, 10, 12],
       [ 8,  9, 10]])

In [79]:
[1121,3,5,7,9,7,78,9]+[1,2,3,4,55,6]

[1121, 3, 5, 7, 9, 7, 78, 9, 1, 2, 3, 4, 55, 6]

In [80]:
ar1*ar2

array([[ 7, 16, 27],
       [16, 25, 36],
       [ 7,  8,  9]])

In [81]:
ar1

array([[7, 8, 9],
       [4, 5, 6],
       [1, 1, 1]])

In [82]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
np.sqrt(ar1)

array([[2.64575131, 2.82842712, 3.        ],
       [2.        , 2.23606798, 2.44948974],
       [1.        , 1.        , 1.        ]])

In [84]:
ar1.sum()

42

In [85]:
ar1.min()

1

In [86]:
ar1.max()

9

In [87]:
ar1

array([[7, 8, 9],
       [4, 5, 6],
       [1, 1, 1]])

In [88]:
np.where(ar1>5)

(array([0, 0, 0, 1], dtype=int64), array([0, 1, 2, 2], dtype=int64))

In [182]:
ar1

array([[7, 8, 9],
       [4, 5, 6],
       [1, 1, 1]])

In [89]:
np.where(ar1>5) #greater than 5 element find krna hai 

(array([0, 0, 0, 1], dtype=int64), array([0, 1, 2, 2], dtype=int64))

In [90]:
type(np.where(ar1>5))

tuple

In [91]:
np.count_nonzero(ar1)

9

In [92]:
np.nonzero(ar1) #np.nonzero(ar1) returns the indices of all non-zero elements in the NumPy array ar1

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [180]:
ar1

array([[7, 8, 9],
       [4, 5, 6],
       [1, 1, 1]])

In [184]:
ar1[1,2]=0

In [186]:
ar1

array([[7, 8, 9],
       [4, 5, 0],
       [1, 1, 1]])

In [188]:
ar1[0,0]=0

In [190]:
ar1

array([[0, 8, 9],
       [4, 5, 0],
       [1, 1, 1]])

In [192]:
# hrr axis ke liye ek tuple mil jata hai 

In [194]:
  np.nonzero(ar1)

(array([0, 0, 1, 1, 2, 2, 2], dtype=int64),
 array([1, 2, 0, 1, 0, 1, 2], dtype=int64))

In [196]:
import sys

In [200]:
py_ar=[0, 0, 1, 1, 2, 2, 2]

In [202]:
np_ar=np.array(py_ar)

In [214]:
sys.getsizeof(1) #sys.getsizeof() tells how much memory an object uses.

28

In [208]:
sys.getsizeof(1)*len(py_ar)

196

In [210]:
np_ar.itemsize*np_ar.size

28

In [212]:
np_ar.itemsize

4

In [216]:
# https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.ndarray.html

In [218]:
np_ar.tolist()

[0, 0, 1, 1, 2, 2, 2]